### ISSUE TITLE
Make the highligth update when editing

### ISSUE THREAD

**Issue by QuentinAM** [metonym/svelte-highlight#281]
Is there a way that it keep highlighting while editing to make it look like an IDE ?

**Comment by metonym** [comment]
For proper editing capabilities, I would recommend a technology like [CodeMirror](https://github.com/metonym/svelte-highlight/issues/236#issuecomment-1239627680).

For `contenteditable` usage, I will consider supporting that, now that Svelte supports `innerText` bindings since [version 3.58](https://github.com/sveltejs/svelte/blob/a83e438b5e43c4012ed7a391968dc196ca88f0a3/packages/svelte/CHANGELOG.md#3580) (tracked in #264).

**Comment by metonym** [comment]
Basic editing is now supported in v7.13.0 via HighlightEditable (https://github.com/metonym/svelte-highlight/pull/423).

It's a lightweight, composable way that supports highlighted editing with basic support for undo/redo/select (and other imperative methods).


```svelte
<script>
  import { HighlightEditable } from "svelte-highlight";
  import typescript from "svelte-highlight/languages/typescript";
  import atomOneDark from "svelte-highlight/styles/atom-one-dark";

  let code = "const add = (a: number, b: number) => a + b";
</script>

<svelte:head>{@html atomOneDark}</svelte:head>

<HighlightEditable language={typescript} bind:code />
```
